server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:JavaDevKanka/fretflex-config.git
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          default-label: master
          search-paths: "{application}"